### ISSUE TITLE
[Question] Is there a way to make Apache Guacamole more fluent but maybe less quality?

### ISSUE THREAD

**Issue by ne0YT** [itiligent/Guacamole-Install#15]
The image quality is perfect but some things can really not be fluent like scrolling etc.

is there any way to make it more fluent by making the quality less or use more bandwidth and calculate less on the client-side?

it really seems to be slow on lower end devices. especially when compared to windows html5 client or KASM Workspace (with linux).

**Comment by itiligent** [comment]
It all depends on many factors inside and outside of Guacamole like network latency an speed, NAT gateway performance and hops, local client software config and load etc. 

Personally I find Ubuntu to be around 1/3 slower in response to a minimal install of Debian on the exact same virtual hardware. Trust me, on Debian Guacamole feels MUCH more snappy. Its even quite usable on Raspi with Raspbian (raspi Ubuntu variants are slow) . You could also try without SSL and reverse proxy as these will have some impact on low power systems - but you sacrifice security in doing so . However, your use case may not need this level of security. Also avoid manually adding the inclkuded extra encyption script that adds TLS between guacamole deamon and client app. 

In general, very low power clients and servers are going to be slower, but you can still mitigate a few other things.. 
In RDP settings for a Guac connection, experiment with removing all enhancements like Enable wallpaper, Enable theming, Enable font smoothing, Enable full-window drag, Enable desktop composition, Enable menu animations, Disable bitmap caching, Disable off-screen caching Disable glyph caching.

**Comment by ne0YT** [comment]
@itiligent 
does it already use websocket?

**Comment by itiligent** [comment]
I'm assuming your'e playing about with Debian 12 or later versnios of Ubuntu to ask that question??
If so heres some extre info to save you wasting time:
Mariadb defaults to websockets yes, even when you specifiy to use a TCP port its behavour still uses websockets - this is in the docs and it is not a good thing but the devs have never fixed it.  Debian 12 and Maria versions from around 10.6  onwards seem to need to have a password set on the database even though you are connecting as root/sudo which breaks some of the Gucamole database setup. (debconf commmands that pre-set db passwords dont seem to work anymore too) I've found that scripting the adding of a root db password and having the gucamole databse customisation tasks authenticate with this password instado of sudo and all works ok. But ther is still the matter of tomcat 10 not being compatible yet.
