### ISSUE TITLE
[BUG] cannot install it as root is not allowed but without root I get permission denied

### ISSUE THREAD

**Issue by ne0YT** [itiligent/Guacamole-Install#16]
I used ubuntu 22.04 with a user which has sudo but
I get a few errors before about not having permissions to write to /root

in the last step it's this error:
checking Linux distro specific dependencies...
./1-setup.sh: line 578: /root/guac-setup/guacamole_1.5.3_setup.log: Permission denied
Failed. See /root/guac-setup/guacamole_1.5.3_setup.log

if I run the setup using sudo or the root-account it will always tell me its not allowed to use root..
so it cannot be setup.

**Comment by itiligent** [comment]
I dont think this is a permissions error. The script works fine on a fresh vanilla ubuntu install 22.x with no issues and I cannot reproduce your error, but I can take an educated guess....  

If you take a look at line 578, this line relates to ensuring the Ubuntu "universe" reporisitory is available. From what I understand, universe is now actually added by default on unbutu builds past 18.x, but this code is left in place to ensure support for these earlier Ubuntu versions. It is therfore likely you have some non default things going on with your repo setup, or you are missing the software-properties-common package which is needed to allow the sudo add-apt-repository -y universe command. Try either commenting out line 578 (as it is likely redundant on a vanillla Ubuntu 22.x server install), or   
`sudo apt-get install software-properties-common` and then re-run.

About sudo permissions use with this setup:  
The scripts need to switch between sudo and non sudo tasks depending on install options selected all whilst keeping these exported enviromental variables common across all scripts. To do this, sudo is called from within the scripts *as needed* with the -E switch which keeps these same variables accross the various scripts. To use sudo at the start of the script you need to add all the scripts together into one gigantic 3000 line script, but this is not a very workable way to manage guacamole install changes over time or to add features.) Running everything as sudo also complicates the prodcution of SSL certificates if the root user is not actually enableld - in this case these and these SSL artefacts and other cron tasks set up at install would not be accessible without enabling the root user - not ideal or compliant to many security baselines for a secure appliance. 

Let me know how you go with the changes I've suggested.

Cheers

**Comment by ne0YT** [comment]
@itiligent 
I use the ubutnu cloud-image form here https://cloud-images.ubuntu.com/jammy/current/
with this I setup my VMs using cloud-init on KVM.

I tried your solution, which installed the package successfully, but I still get the same error about not having permissions for /root/..
```
sudo apt-get install software-properties-common
```

**Comment by itiligent** [comment]
Ok, so the cloud-init thing was important info to provide upfront. 
Yours is not not a vanilla Ubuntu install. Cloud-init images need a fair bit of custom config as they are very minimal to start with. You need to build your own image script based on the config you want.  Are you using the default cloud-init user? (this may not have full sudo rights)  Have you set up a full sudo user? have you tried enabling root? 
[https://www.youtube.com/watch?v=GyVWQsdZqOM](url) 

This is a cloud-init support and permissions issue, not a script bug.

**Comment by ne0YT** [comment]
@itiligent 
I have a normal sudo user. and I also enabled the root account.
I use this same setup for all services I install on ubuntu and never had an issue.
it seems as there is a depency missing but what could it be.

**Comment by itiligent** [comment]
as is said, the cloud init images are very minimal and you need to build them with all the software you might need. they might also have additional security baselines configured that limit OS and filesystems access , or only allow signed software etc. There is a difference between installing other services and building software...are you building and other services with the same sudo account?

The only way to debug your issue is to research the differences between a regular install and cloud init. Start by listing all the packages the script calls, and then install these one by one manually to see what breaks. then manually step through the commands of the script.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by itiligent** [comment]
I've taken a quick look at the latest cloud images... You are using the daily updated images! 
These are now very close to Debian 12 which is also broken with Guacamole right now. Theres a range of issues already documented in another open issue around database timezones and other permissions etc, plus tomcat is not compaitible with curent versions of guac. I see the same install errors with this cloud image as I do with Debian 12. These cloud images are hardedned slightly too so you need to be able to tweak the script to work around this in the areas of database defaults,  I think you are way too close to the bleeding edge with your expectations by using daily images, especially so close to recent major releases of late.  Roll back to an earlier stable image version, or just use Debian 11 if you really want performance. I wont be updating the script to work around all these changes till the Guac devs have done their bit else I'll be just spinning wheels with nothing to test.

**Comment by ne0YT** [comment]
@itiligent thx for testing :)

**Comment by itiligent** [comment]
It does work, I just tested in on a Ubuntu 22.04 LTS cloud image.. Installs just fine.  
[https://cloud-images.ubuntu.com/releases/22.04/](url)
I jut installed the oldest release, then ra na full update, then installed Gucamole and Nginx with zero issues.
You have to use SEVER RELEASE IMAGES, not jammy dailies as these are closer to rolling(ish) versions... and its not realistic to expect production software outside of repo packags to keep up with daily updates. Stick with releases and you'll always have a better experience.
