### ISSUE TITLE
Dark to Light

### ISSUE THREAD

**Issue by thytetgc** [itiligent/Guacamole-Install#19]
How to change the theme to the default White?

**Comment by itiligent** [comment]
Hi,
Please see the readme...
*"branding.jar: An example template for customising Guacamole's UI theme. Delete to keep the default UI."*
So, this means delete branding.jar from /etc/guacamole/extensions and the default guac theme will return. Alternatively, see the  [theme builder notes](https://github.com/itiligent/Guacamole-Install/tree/main/guac-custom-theme-builder)  where you can make/modify the css template to produce whatever custom look your want.
