### ISSUE TITLE
E: Frozen packages have been modified and -y has been used in --allow-change-held-packages.

### ISSUE THREAD

**Issue by Coubiac** [itiligent/Guacamole-Install#20]
I have this error on a fresh Debian 12 install:
E: Frozen packages have been modified and -y has been used in --allow-change-held-packages.

**Comment by itiligent** [comment]
Thanks for lettme me know.  
This was my bad. A few says ago I'd added a package hold for Ubuntu but also mistakenly added it to Debian 12.  Its fixed and working now.
