### ISSUE TITLE
API calls not working from PostMan but curl is OK

### ISSUE THREAD

**Issue by petender** [itiligent/Guacamole-Install#24]
Hi, I don't think this is an issue with the setup, but I tried about anything and can't figure out why... maybe you can help?

My setup is Debian12, with all defaults from your setup script. I tried getting a token using Postman POST call to http://publicip/guacamole/api/tokens, which gives "internal server error 305". Browser features for guacamole all work (create users, connections,...)

From here, I did a new setup, adding Nginx and LetsEncrypt for a public domain, assuming an issue with proxying/not allowing API requests on http.

Still same in Postman... however, when trying the same from Curl commands, it works fine (create user, create connection,...). 

So it "somewhat works", but not 100%. Eventually, I want to trigger HTTP API Requests from Azure LogicApps. 

Is there anything I could check in my setup which would lead me to the rootcause why PostMan is not working? happy to share more details about my setup

**Comment by petender** [comment]
Did some additional testing, and - when I create a new TOKEN from curl, and add this to the Header Key in Postman, I succeed in creating the user. It seems just getting a token is not working... wondering what I'm missing as settings/parameters/...

**Comment by itiligent** [comment]
Thanks for the extra background, and I'm glad you're using this for somthing a bit more complex and interesting!  
Those sorts of issues feel like an encryption sesssion is not being able to do its thing. 
Try and remove Nginx from the equasion. Run up a test without just the guacamole and no Nginx/SSL. Look at you guac logs (Tomcat also have a "valve"  config that forces the client's local IP to be passed though Nginx untouched so the gucamole log files are accurate and dont show the nginx IP - but this might play problems with the token negotiation.

**Comment by itiligent** [comment]
For what its worth, I can remotely create a new test users with the following API commands  between Debian 12 & Ubuntu 23 systems. You will need to make sure jq is installed on Debian 12.  Botht systems were setup with the script defaults and wuth Nginx self signed TLS.

```
export TOKEN=$(curl -s -k -X POST https://localhost/api/tokens -d 'username=guacadmin&password=guacadmin' | jq -r .authToken)

curl -s -k -X POST -H 'guacamole-token: '$TOKEN -H 'Content-Type: application/json' https://x.x.x.x/api/session/data/mysql/users --data-binary '{"password":"testpassword","username":"newuser","attributes":{}}'
```
This reference seems to be pretty clear. Not sure how you will use HTTP only for these commands though.
[https://docs.netcubed.io/products/guacamole/api](https://docs.netcubed.io/products/guacamole/api)

**Comment by itiligent** [comment]
if you remove Nginx and test and Postman works, could be an encoding issue nginx handles http.
[https://stackoverflow.com/questions/59641821/nginx-fails-to-pass-of-post-request-body-when-proxying-requests-to-an-express-ba](https://stackoverflow.com/questions/59641821/nginx-fails-to-pass-of-post-request-body-when-proxying-requests-to-an-express-ba)

**Comment by petender** [comment]
Hey, thanks for picking this up and trying to help brainstorming into getting this solved. I knew through curl it was working, so the Guac setup itself seemed ok. And I had it running OK in the past (2 years ago), as I had screenshots in a doc :). Based on that, I managed to go back to Postman using an account from the past, where I saved my settings - to find out how I got it working at that time:

Instead of using the "Authorization" settings within Postman, and specifying username/pw there, I had it defined in the Body section as x-www-form-URLencoded parameters, one for username and one for password. 

Which provides me with an authorization token as expected. 

Next, I checked the code section within Postman, which showed me it's adding an Authorization section in the Header, for the basic authentication. 

Which eventually got me in succeeding running the same HTTP trigger task from Azure Logic Apps, after I provided the Authorization parameter in the Header section of the HTTP Connector/Task as well, next to providing the Authentication settings in that HTTP connector as well. 

No clue why I have to provide both built-in Authentication credentials on the connector, as well as specifying in the Header it is using basic authentication, but hey - working is working...

**Comment by itiligent** [comment]
Cool I'm glad you got it sorted. Thanks for sharing this coz API has not been by focus and now I've learned something new!

**Comment by petender** [comment]
Nice. Me on the other side, have mainly been using Guacamole from the API features, as it nicely integrates in automated Azure VM deployments, offering labVM scenario to students. So if you ever want to go that route more, feel free to reach out. There's not too many options to know off, allowing for automatic user, connections and integrating both are the main things I'm using from it. But also exploring other options to enable more features where needed. Thanks, Peter

**Comment by itiligent** [comment]
I originally went to the trouble of assembling this whole Guac build system as I too was taking students through secure administration and operational management aspects with Guacamole, but most students couldn't handle this level of build on their own. And lets face it, without an idiot proof build script Guac is a supper pain to manuallly build (and docker is tool tha just moves the compextiy to another dept.)  

I've spent a long time getting this Guac build into something enterprise worthy as this is my background. As such I'd love to see a working example of a real world lab or automation/orchestrion/IaC scenario that you describe.  I'd be happy to look at any extra Guac config features and options if you've got any special build requirements too - I suspect Oauth/OIDC and the like might be something useful in future? Let me know if there's any gaps there.
