### ISSUE TITLE
Compuer no longer able to access the internet - Running Setup.sh

### ISSUE THREAD

**Issue by JustMentalMatt** [itiligent/Guacamole-Install#25]
OS: Ubuntu 20.04.3 LTS

Upon running setup.sh and going through the process of installing, i restarted my pc - i then tried to remote back into my pc and that didnt work. after trying multiple methods of remote access i was forced to connect a screen up to it. My ETHERNET symbol in the top right corner has a question mark going through it, meaning it has failed connectivity tests. I cannot google anything as all i get is a server error, and i cannot request info from websites previously published by this same server computer. All of my servers and sites are down at the minute which is a bit unfortunate :(

I have tried resetting resolv.conf, reassigning my PC a new port on my router. As far as i can tell, it is the computer at fault, as the router is recognising it being connected and has an IP assigned to it.

I just want to know what the setup.sh script changes in regards to my network management as i am clueless right now.

I tried running: 
`sudo tail -f /var/log/syslog /var/log/tomcat*/*.out guac-setup/guacamole_setup.log`
> https://imgur.com/a/luS2d9D
- this is followed by several logs of different applications trying to access databases, or form connections, all of which are errors.
*im aware the logs might contain sensitive info, for troubleshooting purposes i can change these later.

**Comment by itiligent** [comment]
When you say "remote" back in to your computer this is not very specific. Its important to decribe the before and after state.
"it didnt work" is not much to go on! The install options you selected are alos important to understand the potential issue/ 

It sounds like you already had some other form of access from outside your network without Guamcamole via port forwarding at your router? It also sounds possible you've installed this on your PC - meaning its your desktop too? If so, please remember this is a script to build a SECURE server appliance.  If you had other uses for the existing machine then the script can't take all these into consideration. If other web sites or services were in existence on 80/8080 or 443 then things will of course conflict.

The only network changes that the script makes is to :
- align hostname/local dns name/server name for TLS to work properly.
- installs the linux firewall and activates rules to force access though either port 80/8080/443 and 22

at the very least, try turning off the firewall and testing again.
`sudo ufw status`  - to see current rules
`sudo ufw  disable` - to test connectivity.

**Comment by itiligent** [comment]
I took a closer look at your log...
If you are running tailscale you may have some issues with 443 and the firewall. google is your friend!
`If you ensure that port UDP/41641 is not blocked, and that outgoing UDP and TCP/443 is permitted, Tailscale will be able to reliably serve direct connections. Opening incoming UDP/41641 (by default) on a device's public IP address will guarantee a direct connection from any peer where it is possible` 
I also see that it looks like you had a failed install. The Dkpg errors in the log occur an install or update task was run and stopped midway.  did you stop and state the script before it finished at any point? (also Ubuntu annoyingly runs unattedded apt updates in the background which also creates havoc and these sorts of errors. Rebooting solves this but its a pain.)

**Comment by itiligent** [comment]
A final thought, always test before running any script.. Dont rush ahead, take some time to read through the install scripts. Run ap a test system to understand how this will work first. I've taken great care to clearly explain the script actions in the comments. This allows you to follow the scripts through all their sequence in a clear order... 1, 2 3, 4a or b.. Just look for the parts that releate to the options you will choose. For example, each script addresses a new firewall config for each install context (no nginx installed, then just allow incoming 8080 etc) You also have to remember the guacamole is a security applicance, so the app has to be locked down. If you're trying to run this on the same system that you host other production sites and systems then you are breaking a number of commonsense rules that will almost always result in conflicts, pain, and reduced security.
