### ISSUE TITLE
Error during install on ubuntu 22.04.3

### ISSUE THREAD

**Issue by aravind365** [itiligent/Guacamole-Install#29]
Install on ESXI 6.5 VM running ubuntu 22.3 Desktop

SQL Error 

Brand new VM. nothing else on it.

Creating the Guacamole database...
ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'N5"; GRANT SELECT,INSERT,UPDATE,DELETE ON guacamole_db.* TO 'guacamole_user'@'lo' at line 1
Failed
2-install-guacamole.sh FAILED. See [/home/adminvgw/guac-setup/guacamole_install.log
[guacamole_install.log](https://github.com/itiligent/Guacamole-Install/files/14145033/guacamole_install.log)

**Comment by itiligent** [comment]
I just re-ran the script and can confirm that the script with all its defaults works absolutely perfectly on Ubuntu 22.04.3  (both server & desktop variants with a default install from the Ubutu ISO). 

BTW this SQL part of the code is years old and well tested.

See $MYSQL_HOST in the silent setup section of the setup script. This should be empty quotes blank "" for a local install only. This is only changed when attaching guac to an external SQL instance.  

It looks like the script is picking up an incomplete "localhost"
the script should be passing  'guacamole_user'@'locolhost'

What script install options did you make? 
Have machine names or hosts been edited? 

Without any real context its not really possible to take this any further (see the issue form for what is required to report an issue)

some examples to think about are:
Which version? (what is Ubuntu 22.3?)
What is the origin of the VM? - was your VM built from your own ISO?, or was it pre-cooked from Ubuntu? a cloud image?
Did you cusomize any of the scripts?
Do you have any other SQL tools or apps installed? 
What has been updated in Ubuntu etc etc

**Comment by itiligent** [comment]
Closing as no further info was provided. The issuse appears to relate to incorrect script settings

**Comment by aravind365** [comment]
Hi,

Thank you for replying so quick ! Sorry for a late reply.

I may have changed the hostname during the first attempt to install. Then when the box didn’t respond, I terminated it and re-tried the wget. I’ve tried it several times and I’m getting different errors.

It’s on a Ubuntu 22.04.3 VM on ESXI 6.5. The VM is from an ISO. 

Please could you kindly advise how I’d wipe out all the stuff that’s been downloaded (to clear up space) and installed (as in a pre-state) so I can try again afresh ?

/etc/hosts shows 

127.0.1.1	Hostnamex
10.10.10.10	Hostnamex.lab.local Hostnamex

My VM has two NIC cards. 

Thanks again !

**Comment by aravind365** [comment]
i just installed guac successfully on another esxi - same ubuntu version. it went in absolutely brilliant - like a breeze ! so, just want to know how i'd erase this faulty one so i can try it all over again.

**Comment by itiligent** [comment]
It is important that the system name & your DNS names line up if you are goung to use SSL. The script alings all this, all you need to make sure of is that there are the same names in your DNS. 

 If you stopped a build halfway through thats a mess I really can't help you with. Looking at the scripts will help you reverse most things (apt remove for all the packages, delete the guac application directories and config files.  I've not built an uninstall facility as the best way when working with VMs is to snapshot prior to installing or making any system changes.
It might be easier to start fresh.
