### ISSUE TITLE
Backup weirdness as did not end backup directory with a / during installation

### ISSUE THREAD

**Issue by Taomyn** [itiligent/Guacamole-Install#32]
**Describe the issue:**
I noticed today that I had not received a notification for the backups in a while, and looking into it, the backup-guac.sh script had disappeared so cron no longer could run it. After I re-downloaded the script, as my backups did not go far enough back for recovery, then during the re-entry of the backup settings and checking through the code I noticed this (lines 46/47): https://github.com/itiligent/Guacamole-Install/blob/631bedd592c9ae7d08f5150dc2cb7cec6e8d71cd/guac-management/backup-guac.sh#L46 there is no / between ${DB_BACKUP_DIR} and ${GUAC_DB}, and I don't think I put one in during the install.

Looking at the cron job, for some reason it was executing the script from the "mysqlbackups" folder, then got deleted due to the 30 day retention, and then all the backup files ended up just in the home folder of the service account, all prefixed "mysqlbackups".

**Steps to reproduce the issue:**
Install but do not end the backup directory with a / - I think!?

**Describe the software environment:**
- OS & version
  - LXC version of Debian 12 running on Proxmox v8

**Troubleshooting steps already taken?:**
I moved the backup-guac.sh script back to the guac-setup directory, added / to lines 46/47 along with setting the parameters, amended the cron job, and moved my backups into the mysqlbackups directory.

**Comment by itiligent** [comment]
Thankf for letting me know.

I could replicate your error. It appears as though some tiny bugs in the backup script that I missed in testing gave the backup some suicidal tendencies after the retention period! 

You fix will work, but I prefer to keep the backup script away from the guac-setup dir as setup files are generally not viewed as operational, and it will be good to allow for the setup diretory to be removed for a future update or just houskeeping.

I've added the missing file path slashes for the backup and zip commands,, and also changed the backup retention/delete command to remove only *.gz files past the max age setting. I've tested by setting the retention age to -1, and all seems to work now.
