### ISSUE TITLE
Update VNC client library

### ISSUE THREAD

**Issue by Taomyn** [itiligent/Guacamole-Install#33]
**Describe the feature or solution you'd like to see included:**
This is probably a long shot, but is it feasible to update the VNC client library that's used by Guacamole? The current one is ancient and has numerous issues being connected by far newer clients without downgrading things.

**Is this feature request related to a problem or specific use case?:**
 My primary motivation is to allow Gucamole to connect to my PiKVM, but it's broken:
 
![image](https://github.com/itiligent/Guacamole-Install/assets/4365929/838ac97a-ba66-44e0-8b5f-d2ae69446fb1)

**Additional context:**
The recommended TigerVNC viewer works just fine, so I know the PiKVM is well set up
Looking through the Guacamole Jira it's down to the library they currently use, libvncclient, so that I think needs replacing but it's not getting done so far even though issues have been reported for years.

**Comment by itiligent** [comment]
Guac VNC support is indeed dictated by the installed version of [libVNCServer](https://guacamole.apache.org/doc/1.2.0/gug/installing-guacamole.html) installed by the script.
However the lastest release of RealVNC is confirmed as 0.9.14 from [here](https://github.com/LibVNC/libvncserver/releases) and is what I see after a sudo apt upgrade (with Debian 12), and is only about 14mth old., and was only added to debian's testing branch last [september](https://tracker.debian.org/pkg/libvncserver)

```
apt list --installed
libvncclient1/stable,now 0.9.14+dfsg-1 amd64 [installed,automatic]
libvncserver-dev/stable,now 0.9.14+dfsg-1 amd64 [installed]
```
I dont know what libVNCserver version you are seeing in your distro, but your choices may be to upgrade distro or downgrade features talked about [here](https://help.realvnc.com/hc/en-us/community/posts/7565341003805-Can-t-connect-to-VNC-server-using-Guacamole-client) and [here](https://www.reddit.com/r/homelab/comments/ncv9ze/apache_guacamole_cant_connect_to_realvnc_server/)

**Comment by Taomyn** [comment]
Hi, thanks for getting back. I did the same check on the libvnc installed on my Guacamole server and they exactly match yours - the strange thing is that retrying my connection to PiKVM is now working. I double-checked everything and nothing else has changed so I'm at a loss as to why.

Previously I was running Guacamole as a Podman container on my Fedora server, but I wanted to get away from that and have it running as an LXC on my Proxmox that also runs my firewall - everything else was working, RDP, VNC to another Proxmox, except to the PiKVM until now. It never worked when running on my Fedora server on any VNC server, so you're build is a vast improvement.
