### ISSUE TITLE
Wrong variable in sed in 2-install-guacamole.sh

### ISSUE THREAD

**Issue by gondimcodes** [itiligent/Guacamole-Install#34]
**Describe the issue:**
In the code snippet below:
sed -i -e 's/IDX_DRIVE_NAME, "Guacamole Filesystem"/IDX_CLIENT_NAME, "'"${RDP_SHARE_LABEL}"'"/' ${DOWNLOAD_DIR}/guacamole-server-${GUAC_VERSION}/src/protocols/rdp/settings .c

I believe the correct thing would be:
sed -i -e 's/IDX_DRIVE_NAME, "Guacamole Filesystem"/IDX_DRIVE_NAME, "'"${RDP_SHARE_LABEL}"'"/' ${DOWNLOAD_DIR}/guacamole-server-${GUAC_VERSION}/src/protocols/rdp/settings .c

In the exchange where it should be IDX_DRIVE_NAME, it is as IDX_CLIENT_NAME.

**Steps to reproduce the issue:**
- Please provide the steps to reproduce the error or behaviour (include what you believe should happen):

**Describe the software environment:**
- OS & version
  - Include platform i.e. physical, virtual, cloud image etc
- List other applications present
- List other services or tasks the system also currently provides
- Details any other relevant background context about your OS, its location, method of management or access, firewall settings etc.

**Logs / screenshots / error outputs etc**
- Where possible, provide as much background detail as possible to help explain your problem through the outputs you have available.

**Troubleshooting steps already taken?:**
- What steps have already taken to diagnose, debug or resolve the issue?
- Details of any testing already performed?

**Comment by itiligent** [comment]
Well spotted, thanks.
