### ISSUE TITLE
Beautiful ! THANK YOU! 

### ISSUE THREAD

**Issue by deanbushmiller** [itiligent/Guacamole-Install#35]
This worked very, very well, including the customization. A lot of my students are using Bastian host in production environments, and I will be singing your praises. I did send a donation. **I put this here so that everybody else might donate a few dollars to keep your project going.**

**Comment by itiligent** [comment]
You're most welcome. 
This project actually was originally built for cybersecurity training content and as a remote worker server farm in response to Covid. I've kept adding to it over the years, and I think my next update will be to add OpenID Connect for SSO.
If your students are buliding bastion hosts,  take a look at the enterprise scripts in the repo for splitting MySQL , guac and front end load balancing into 3 separate layers, then encrypt all internal guac traffic to produce a similar architecure to CyberArk.
