### ISSUE TITLE
Installation failled

### ISSUE THREAD

**Issue by 3th3r** [itiligent/Guacamole-Install#37]
**Describe the issue:**
- On a fresh debian12 LXC  install, with a Sudo users, script executed in the home user directory

**Steps to reproduce the issue:**
- use the script, spew an error message: Failed. See //guac-setup/guacamole_install.log

**Describe the software environment:**
- LXC debain 12

**Logs / screenshots / error outputs etc**
Synchronising the install script suite with the selected installation options...
sed: can't read //guac-setup/backup-guac.sh: No such file or directory
sed: can't read //guac-setup/backup-guac.sh: No such file or directory
sed: can't read //guac-setup/backup-guac.sh: No such file or directory
sed: can't read //guac-setup/backup-guac.sh: No such file or directory
sed: can't read //guac-setup/backup-guac.sh: No such file or directory
sed: can't read //guac-setup/backup-guac.sh: No such file or directory
sed: can't read //guac-setup/backup-guac.sh: No such file or directory
sed: can't read //guac-setup/backup-guac.sh: No such file or directory
sed: can't read //guac-setup/add-tls-guac-daemon.sh: No such file or directory
sed: can't read //guac-setup/add-tls-guac-daemon.sh: No such file or directory
sed: can't read //guac-setup/add-tls-guac-daemon.sh: No such file or directory
sed: can't read //guac-setup/add-tls-guac-daemon.sh: No such file or directory
sed: can't read //guac-setup/add-tls-guac-daemon.sh: No such file or directory
sed: can't read //guac-setup/add-tls-guac-daemon.sh: No such file or directory
sed: can't read //guac-setup/upgrade-guac.sh: No such file or directory
sed: can't read //guac-setup/upgrade-guac.sh: No such file or directory
sed: can't read //guac-setup/upgrade-guac.sh: No such file or directory
sed: can't read //guac-setup/upgrade-guac.sh: No such file or directory
sed: can't read //guac-setup/upgrade-guac.sh: No such file or directory
sed: can't read //guac-setup/upgrade-guac.sh: No such file or directory
sed: can't read //guac-setup/upgrade-guac.sh: No such file or directory
sed: can't read //guac-setup/3-install-nginx.sh: No such file or directory
sed: can't read //guac-setup/3-install-nginx.sh: No such file or directory
sed: can't read //guac-setup/3-install-nginx.sh: No such file or directory
sed: can't read //guac-setup/4a-install-tls-self-signed-nginx.sh: No such file or directory
sed: can't read //guac-setup/4a-install-tls-self-signed-nginx.sh: No such file or directory
sed: can't read //guac-setup/4a-install-tls-self-signed-nginx.sh: No such file or directory
sed: can't read //guac-setup/4a-install-tls-self-signed-nginx.sh: No such file or directory
sed: can't read //guac-setup/4a-install-tls-self-signed-nginx.sh: No such file or directory
sed: can't read //guac-setup/4a-install-tls-self-signed-nginx.sh: No such file or directory
sed: can't read //guac-setup/4a-install-tls-self-signed-nginx.sh: No such file or directory
sed: can't read //guac-setup/4a-install-tls-self-signed-nginx.sh: No such file or directory
sed: can't read //guac-setup/4a-install-tls-self-signed-nginx.sh: No such file or directory
sed: can't read //guac-setup/4a-install-tls-self-signed-nginx.sh: No such file or directory
sed: can't read //guac-setup/4a-install-tls-self-signed-nginx.sh: No such file or directory
sed: can't read //guac-setup/4a-install-tls-self-signed-nginx.sh: No such file or directory
sed: can't read //guac-setup/4b-install-tls-letsencrypt-nginx.sh: No such file or directory
sed: can't read //guac-setup/4b-install-tls-letsencrypt-nginx.sh: No such file or directory
sed: can't read //guac-setup/4b-install-tls-letsencrypt-nginx.sh: No such file or directory
sed: can't read //guac-setup/4b-install-tls-letsencrypt-nginx.sh: No such file or directory
sed: can't read //guac-setup/4b-install-tls-letsencrypt-nginx.sh: No such file or directory
sed: can't read //guac-setup/4b-install-tls-letsencrypt-nginx.sh: No such file or directory
sed: can't read //guac-setup/add-smtp-relay-o365.sh: No such file or directory

**Comment by itiligent** [comment]
Without knowing any of your specifc container config or other troubleshooting steps I can only say that the log file is directly telling you there is likely a persmissions issue or some other file path issue with the download location of the suite of scripts.  

Have you at least looked to see if the script files successully downloaded? The log file is your friend! 

Also look at the script's contents to understand what it is trying to do (it is trying to find the downloaded files listed in the log above and edit these to your chosen setup options)  You will need to translate the script's actions to your own enviroment especially if your container config ventures away from the default Debian 12 install from ISO. 

Also, check the reamdme - is sudo installed? You need to make sure that your container config is not limiting the script from running as it expects. Although I dont directly test or support LXC install, I am aware of others that have succesfully deployed this in LXC with zero issues.

**Comment by itiligent** [comment]
closed due to no further input regarding troublshooting actions taken.
