### ISSUE TITLE
Compatibility with Ubuntu 24.04 and Tomcat10

### ISSUE THREAD

**Issue by Biturbogolf** [itiligent/Guacamole-Install#38]
I used your very cool script for installing Guacamole.

But an Ubuntu 24.04 and Tomcat10 I get a HTTP status 404 and Tomcat gives the message "The requested resource [/guacamole] is not available".

For me it is very important to use Ubuntu with tomcat10, because our vulnerability managment system says their are a lot of issus at tomcat9 :-(

I hope it is possible to update your script for the new Ubuntu version.

**Comment by itiligent** [comment]
Here's a little background for you:
There are some very large differences between Tomcat 9 and 10, and use of Tocat 10 will apparently require a bunch of reworking by the Guacamole devs. I've looked into this and from what I can see there is acknowelgement that Guac will need to be updated for compatibility with Tomcat 10 at some stage, but when I checked last month there are as yet no development timelines set for when this might happen. 

I hope this Tomcat upgrade (maybe Guacamole 1.6?) happens at some stage soon as keeping newer distros working with Tomcat 9 will eventually become a headache for me to support in the scripts moving forward.

**Comment by itiligent** [comment]
For those looking for an answer on Guac compatibiltiy with Tomcat 10, see here:
https://issues.apache.org/jira/browse/GUACAMOLE-1325

**Comment by Biturbogolf** [comment]
Many thanks for your answers.

I found this issu too. I hope they find a good solution. For example a migration tool for guacamole.

BR

**Comment by itiligent** [comment]
Just a thought, if Tomcat 9 vulberabilities are a concern, be aware there will also be issues in Tomcat 10 -  your vuln mgmt system will throw up isssues for both. Vuln mgmt is more about informed risk mgmt, not shooting for a perfect score on a report. Applying mitigations is hwo you work around these realities. 
For example, take a look and my script and notes on setting up a 3 tiered system so Tomcat can live in its own locked down VLAN as well as a separated VLAN for the Nginx front end and MTSQY backend. You can also encrypt guac server to guac client trafffc with the script provieded. Then you can apply a CIS Ubuntu lockdown template and also add MFA to use sudo - Right there is 99% of the vulnerabilties foorprint covered right there and a system that will pass a lot of govt level compliance requirements.
