### ISSUE TITLE
[question] Where is the upgrade script located?

### ISSUE THREAD

**Issue by CrazyWolf13** [itiligent/Guacamole-Install#42]
Hi
Maybe a little silly question, but where do I find the upgrade script mentioned to update guacamole?

In the folder I started the initially guacamole-installer there is only 1_installer.sh

Thanks!

**Comment by itiligent** [comment]
FYI it is copied to $HOME/guac-setup after install when using the auto setup link, or in the oot of the repo download if you used git clone.

**Comment by CrazyWolf13** [comment]
Yup, by default my lxc's only have a root user, and I couldn't find it there, then I remembered I had created a separate user with another home dir.

Have found it now, so ticket can be closed.
