### ISSUE TITLE
Does not work after the update

### ISSUE THREAD

**Issue by rikirrr** [itiligent/Guacamole-Install#44]
After the update (6 hours ago), the installer stopped working.
At startup, it installs something very quickly (2 seconds) and that's it (it used to take longer)
At the end, I get this conclusion:

```
Guacamole 1.5.5 Auto Installer.
 Powered by Itiligent


Beginning Guacamole setup...

Synchronising the install script suite with the selected installation options...
OK

Guacamole install complete
http://guac.local:8080 - login user/pass: guacadmin/guacadmin
***Be sure to change the password***
no crontab for kirill

Removing build-essential packages...
OK

Guacamole 1.5.5 install complete! 
```

But when trying to access the site, he writes to me that it is not possible to connect, I decided to check something, and that's what I noticed:

```
kirill@deb1:~$ systemctl status guacd
Unit guacd.service could not be found.
kirill@deb1:~$ systemctl status tomcat9
Unit tomcat9.service could not be found.
```

I am using debian 12.4 + gnome on Oracle VM

**Comment by itiligent** [comment]
Thanks for letting me know.  Note to self: dont answer the phone when in the middle of a line of code! This was was just a paste error I made earlier today. I've tested on Debian 12 and its all working again now.
