### ISSUE TITLE
RDP hanging after 1.5.5 Update

### ISSUE THREAD

**Issue by morphyxz** [itiligent/Guacamole-Install#45]
**Describe the issue:**
- The RDP Connection does not load. Screen hangs at "Connecting to Guacamole. Please wait..". No error.

**Steps to reproduce the issue:**
- Use Version 1.5.4 by Itiligent
- Change "NEW_GUAC_VERSION" and "NEW_MYSQLJCON" to 1.5.5 and 8.4.0 in "upgrade-guac.sh" file.
- Run the script with sudo

**Describe the software environment:**
- Ubuntu 22.04 LXC
  - Virtual, on Proxmox
- No other applications
- No other tasks
- Just a regular LXC on a proxmox server

**Logs / screenshots / error outputs etc**
![Screenshot 2024-07-16 104638](https://github.com/user-attachments/assets/23c491ad-68b8-4489-ac56-3251a90a8baa)
![Screenshot 2024-07-16 105009](https://github.com/user-attachments/assets/79dc859d-52f1-4de0-94e4-3e3eefe078f8)
![Screenshot 2024-07-16 105223](https://github.com/user-attachments/assets/4a037224-d233-4c15-aa71-2570f0941211)
![Screenshot 2024-07-16 105253](https://github.com/user-attachments/assets/b2290c40-c3c8-4fa2-a6c2-46c4fe674e1e)

**Troubleshooting steps already taken?:**
- I am a bit lost so far. I have loaded the backup of 1.5.4 and everything works. But we definitely would like to upgrade to fix the RDP leak.. even if only internally.
- The Debug console shows no obvious errors (see picture).

**Comment by itiligent** [comment]
Unfortuantely I cannot reproduce your error. I have just run up a fresh Debian 12 system and installed 1.5.4 with the 1-setup.sh script, and then tested that RDP is working to a local windows 10 instance. I then upgraded via the upgrade-guac.sh script to 1.55 and RDP sessions continue to work fine for me.

The upgrade script is a very simple mirror of the build script, so not much to go wronog in there. When this sort of thing happens it is often something perhaps not right in the initial build, or changed with upgraded packages. 

- Have you upgraded this system from another (even earlier) build? 
- Maybe try to comment out the `apt-get upgrade -qq -y` in 2-install-guacamole.sh and try again to skip LXC package updates 
- Also check to see if you can create other connections in ssh (Broken crypto packages have been an issue in the past)
- Must check all the other usual suspects like syslogs/firewall or even wireshark.  
- You could also try installing fresh but done select to install SQL locally, and insted pointing the new install to the exisiting (local 127.0.01 mysql database - the detail in the high availabilty part of the readme exaplains this a little more.

**Comment by itiligent** [comment]
I forogt to mention - before you do anything else, try creating a NEW rdp connection for your windows system in the Guac console AFTER upgrade - I've had success doing this with broken connections.

**Comment by morphyxz** [comment]
Thank you for your time and fast answer. That's unfortunate for me. Glad it does not happen to others though. I setup the server with 1.5.4. I will try the quick fixes but at some point it's just faster to start from scratch with 1.5.5 on a VM. (Something tells me it's a LXC issue.. I've had those before!) Thanks to your hard work this won't take me long. Creating a new RDP connection first... tomorrow. I will report back

**Comment by morphyxz** [comment]
Recreating the connections from scratch after the update has resolved the issue! Thank you!

**Comment by itiligent** [comment]
Glad you got it sorted. Thanks for getting back. I've slightly edited this issue content for extra clarity to help others who may bump into the same issue.
